---
name: test

on:
  push:
    branches-ignore: [debian]
  pull_request:

jobs:
  test:
    name: ${{ matrix.redmine }} on ${{ matrix.ruby }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - ruby: "3.1"
            redmine: "5.0.2"
          - ruby: "3.0"
            redmine: "5.0.2"
          - ruby: "2.7"
            redmine: "4.2.7"
          - ruby: "2.6"
            redmine: "4.1.7"
      fail-fast: false

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 10
      BUNDLE_WITHOUT: development
      REDMINE_VERSION: ${{ matrix.redmine }}

    steps:
      - uses: actions/checkout@master

      - name: setup postgres
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createuser -s ${USER}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: True

      - name: setup cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: v3-ruby-${{ matrix.ruby }}-redmine-${{ matrix.redmine }}

      - name: setup redmine ${{ matrix.redmine }}
        run: ./redmine update

      - name: run tests
        run: ./redmine exec bundle exec rspec --color

  rubocop:
    runs-on: ubuntu-20.04

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 10
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: True

      - run: bundle exec rubocop --fail-level E --extra-details --display-time --color
